# Generated by Django 4.1.6 on 2023-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('country_of_origin', models.CharField(max_length=200)),
                ('native_language', models.CharField(max_length=200)),
            ],
        ),
    ]
