# Generated by Django 4.1.6 on 2023-02-13 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField()),
                ('primary_language', models.CharField(choices=[('ZH', '中文'), ('ES', 'Español'), ('EN', 'English'), ('HI', 'हिन्दी-उर्दू'), ('AR', 'العربية'), ('BN', 'বাংলা'), ('PT', 'Português'), ('RU', 'Русский'), ('FR', 'Français'), ('HE', 'עברית')], default='ZH', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='profiles',
            field=models.ManyToManyField(to='main_app.profile'),
        ),
    ]
