# Generated by Django 4.1.6 on 2023-02-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_post_profiles_delete_profile'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='primary_language',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='main_app.post'),
        ),
    ]
